# Sample compose file with all settings in the stack.env file
services:
  docker-backup:
    image: ghcr.io/jnslr/docker-backup:main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "8000:80"
    env_file:
      - stack.env