# Compose file for local building the image
# Run with: docker-compose up
# Force rebuild: docker compose up --build
services:
  docker-backup:
    image: docker-backup
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    env_file:
      - stack.env